#!/bin/bash -ex

export DEBIAN_FRONTEND=noninteractive
apt-get -y install mysql-server mysql-client libmysqlclient15-dev

# MySQL should now be running

# We could set the MySQL root password here, but for simplicity
# we leave it blank (no external access is available anyway)